import { lazy } from 'react';

export const DashboardPage = lazy(() => import('../pages/DashboardPage'));
export const AnalyticsPage = lazy(() => import('../pages/AnalyticsPage'));
export const RecordsPage = lazy(() => import('../pages/RecordsPage'));
export const WorkoutsPage = lazy(() => import('../pages/WorkoutsPage'));
export const HistoryPage = lazy(() => import('../pages/HistoryPage'));
export const InsightsPage = lazy(() => import('../pages/InsightsPage'));
export const GoalsPage = lazy(() => import('../pages/GoalsPage'));
export const ProfilePage = lazy(() => import('../pages/ProfilePage'));
export const WorkoutBuilderPage = lazy(() => import('../pages/WorkoutBuilderPage'));
export const ActiveSessionPage = lazy(() => import('../pages/ActiveSessionPage'));
export const SessionSummaryPage = lazy(() => import('../pages/SessionSummaryPage'));
export const ExerciseCatalogPage = lazy(() => import('../pages/ExerciseCatalogPage'));
export const OnboardingPage = lazy(() => import('../pages/OnboardingPage'));
export const AIChatPage = lazy(() => import('../pages/AIChatPage'));
export const WorkoutGeneratorPage = lazy(() => import('../pages/WorkoutGeneratorPage'));
export const NutritionPlannerPage = lazy(() => import('../pages/NutritionPlannerPage'));
export const ProgressAnalysisPage = lazy(() => import('../pages/ProgressAnalysisPage'));
export const AIInsightsPage = lazy(() => import('../pages/AIInsightsPage'));
