export enum PersonalRecordType {
  HEAVIEST_WEIGHT = 'HEAVIEST_WEIGHT',
  MOST_REPS = 'MOST_REPS',
  HIGHEST_VOLUME = 'HIGHEST_VOLUME',
  LONGEST_SESSION = 'LONGEST_SESSION',
  MOST_SETS = 'MOST_SETS',
}